"""
LPConcentratedARBUSDC Strategy Package.

Generated by: almanak strat new
"""

try:
    from .strategy import LPConcentratedARBUSDCStrategy
except ImportError:
    from strategy import LPConcentratedARBUSDCStrategy

__all__ = [
    "LPConcentratedARBUSDCStrategy",
]
